---
ansible_python_interpreter: /usr/bin/python3
ansible_user: j
go_version: 1.24.0
cosmos_version: v22.2.0
cosmos_node_name: mytestnode65
cosmos_chain_id: cosmoshub-4
block_service: https://rpc.cosmos.bh.rocks:443
block_offset: 2000
